# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: exchange.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='exchange.proto',
  package='exchange',
  syntax='proto3',
  serialized_options=_b('\n\032ru.spbstu.kspt.librarylinkB\010Exchange'),
  serialized_pb=_b('\n\x0e\x65xchange.proto\x12\x08\x65xchange\"\xee\x01\n\x07Request\x12\x32\n\x0bmethod_call\x18\x01 \x01(\x0b\x32\x1b.exchange.MethodCallRequestH\x00\x12.\n\x0bimportation\x18\x02 \x01(\x0b\x32\x17.exchange.ImportRequestH\x00\x12\x34\n\x0c\x63onstruction\x18\x03 \x01(\x0b\x32\x1c.exchange.ConstructorRequestH\x00\x12\x0e\n\x04\x65val\x18\x04 \x01(\x08H\x00\x12\x19\n\x0f\x64ynamic_inherit\x18\x05 \x01(\x08H\x00\x12\x13\n\x0b\x61ssigned_id\x18\x07 \x01(\tB\t\n\x07request\"\x8c\x01\n\x11MethodCallRequest\x12\x13\n\x0bmethod_name\x18\x01 \x01(\t\x12\x11\n\tobject_id\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x08 \x01(\t\x12\x1f\n\x03\x61rg\x18\x03 \x03(\x0b\x32\x12.exchange.Argument\x12\x0e\n\x06static\x18\x04 \x01(\x08\x12\x10\n\x08property\x18\x06 \x01(\x08\"\x94\x01\n\x08\x41rgument\x12-\n\x04type\x18\x01 \x01(\x0e\x32\x1f.exchange.Argument.ArgumentType\x12\x1e\n\x05value\x18\x03 \x01(\x0b\x32\x0f.exchange.Value\x12\x0b\n\x03key\x18\x04 \x01(\t\",\n\x0c\x41rgumentType\x12\x0f\n\x0bPERSISTENCE\x10\x00\x12\x0b\n\x07INPLACE\x10\x01\"S\n\x05Value\x12\x16\n\x0cstring_value\x18\x02 \x01(\tH\x00\x12\x13\n\tint_value\x18\x03 \x01(\x10H\x00\x12\x14\n\nuint_value\x18\x05 \x01(\x06H\x00\x42\x07\n\x05value\"&\n\rImportRequest\x12\x15\n\rimported_name\x18\x01 \x01(\t\"I\n\x12\x43onstructorRequest\x12\x12\n\nclass_name\x18\x01 \x01(\t\x12\x1f\n\x03\x61rg\x18\x02 \x03(\x0b\x32\x12.exchange.Argument\"v\n\x0f\x43hannelResponse\x12\'\n\x0creturn_value\x18\x01 \x01(\x0b\x32\x0f.exchange.ValueH\x00\x12\x1b\n\x11\x65xception_message\x18\x03 \x01(\tH\x00\x12\x13\n\x0b\x61ssigned_id\x18\x07 \x01(\tB\x08\n\x06resultB&\n\x1aru.spbstu.kspt.librarylinkB\x08\x45xchangeb\x06proto3')
)



_ARGUMENT_ARGUMENTTYPE = _descriptor.EnumDescriptor(
  name='ArgumentType',
  full_name='exchange.Argument.ArgumentType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PERSISTENCE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INPLACE', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=517,
  serialized_end=561,
)
_sym_db.RegisterEnumDescriptor(_ARGUMENT_ARGUMENTTYPE)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='exchange.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='method_call', full_name='exchange.Request.method_call', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='importation', full_name='exchange.Request.importation', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='construction', full_name='exchange.Request.construction', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='eval', full_name='exchange.Request.eval', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dynamic_inherit', full_name='exchange.Request.dynamic_inherit', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='assigned_id', full_name='exchange.Request.assigned_id', index=5,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='request', full_name='exchange.Request.request',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=29,
  serialized_end=267,
)


_METHODCALLREQUEST = _descriptor.Descriptor(
  name='MethodCallRequest',
  full_name='exchange.MethodCallRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='method_name', full_name='exchange.MethodCallRequest.method_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='object_id', full_name='exchange.MethodCallRequest.object_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='exchange.MethodCallRequest.type', index=2,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='arg', full_name='exchange.MethodCallRequest.arg', index=3,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='static', full_name='exchange.MethodCallRequest.static', index=4,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='property', full_name='exchange.MethodCallRequest.property', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=270,
  serialized_end=410,
)


_ARGUMENT = _descriptor.Descriptor(
  name='Argument',
  full_name='exchange.Argument',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='exchange.Argument.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='exchange.Argument.value', index=1,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key', full_name='exchange.Argument.key', index=2,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ARGUMENT_ARGUMENTTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=413,
  serialized_end=561,
)


_VALUE = _descriptor.Descriptor(
  name='Value',
  full_name='exchange.Value',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='string_value', full_name='exchange.Value.string_value', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='int_value', full_name='exchange.Value.int_value', index=1,
      number=3, type=16, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uint_value', full_name='exchange.Value.uint_value', index=2,
      number=5, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='value', full_name='exchange.Value.value',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=563,
  serialized_end=646,
)


_IMPORTREQUEST = _descriptor.Descriptor(
  name='ImportRequest',
  full_name='exchange.ImportRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='imported_name', full_name='exchange.ImportRequest.imported_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=648,
  serialized_end=686,
)


_CONSTRUCTORREQUEST = _descriptor.Descriptor(
  name='ConstructorRequest',
  full_name='exchange.ConstructorRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='class_name', full_name='exchange.ConstructorRequest.class_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='arg', full_name='exchange.ConstructorRequest.arg', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=688,
  serialized_end=761,
)


_CHANNELRESPONSE = _descriptor.Descriptor(
  name='ChannelResponse',
  full_name='exchange.ChannelResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='return_value', full_name='exchange.ChannelResponse.return_value', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exception_message', full_name='exchange.ChannelResponse.exception_message', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='assigned_id', full_name='exchange.ChannelResponse.assigned_id', index=2,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='result', full_name='exchange.ChannelResponse.result',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=763,
  serialized_end=881,
)

_REQUEST.fields_by_name['method_call'].message_type = _METHODCALLREQUEST
_REQUEST.fields_by_name['importation'].message_type = _IMPORTREQUEST
_REQUEST.fields_by_name['construction'].message_type = _CONSTRUCTORREQUEST
_REQUEST.oneofs_by_name['request'].fields.append(
  _REQUEST.fields_by_name['method_call'])
_REQUEST.fields_by_name['method_call'].containing_oneof = _REQUEST.oneofs_by_name['request']
_REQUEST.oneofs_by_name['request'].fields.append(
  _REQUEST.fields_by_name['importation'])
_REQUEST.fields_by_name['importation'].containing_oneof = _REQUEST.oneofs_by_name['request']
_REQUEST.oneofs_by_name['request'].fields.append(
  _REQUEST.fields_by_name['construction'])
_REQUEST.fields_by_name['construction'].containing_oneof = _REQUEST.oneofs_by_name['request']
_REQUEST.oneofs_by_name['request'].fields.append(
  _REQUEST.fields_by_name['eval'])
_REQUEST.fields_by_name['eval'].containing_oneof = _REQUEST.oneofs_by_name['request']
_REQUEST.oneofs_by_name['request'].fields.append(
  _REQUEST.fields_by_name['dynamic_inherit'])
_REQUEST.fields_by_name['dynamic_inherit'].containing_oneof = _REQUEST.oneofs_by_name['request']
_METHODCALLREQUEST.fields_by_name['arg'].message_type = _ARGUMENT
_ARGUMENT.fields_by_name['type'].enum_type = _ARGUMENT_ARGUMENTTYPE
_ARGUMENT.fields_by_name['value'].message_type = _VALUE
_ARGUMENT_ARGUMENTTYPE.containing_type = _ARGUMENT
_VALUE.oneofs_by_name['value'].fields.append(
  _VALUE.fields_by_name['string_value'])
_VALUE.fields_by_name['string_value'].containing_oneof = _VALUE.oneofs_by_name['value']
_VALUE.oneofs_by_name['value'].fields.append(
  _VALUE.fields_by_name['int_value'])
_VALUE.fields_by_name['int_value'].containing_oneof = _VALUE.oneofs_by_name['value']
_VALUE.oneofs_by_name['value'].fields.append(
  _VALUE.fields_by_name['uint_value'])
_VALUE.fields_by_name['uint_value'].containing_oneof = _VALUE.oneofs_by_name['value']
_CONSTRUCTORREQUEST.fields_by_name['arg'].message_type = _ARGUMENT
_CHANNELRESPONSE.fields_by_name['return_value'].message_type = _VALUE
_CHANNELRESPONSE.oneofs_by_name['result'].fields.append(
  _CHANNELRESPONSE.fields_by_name['return_value'])
_CHANNELRESPONSE.fields_by_name['return_value'].containing_oneof = _CHANNELRESPONSE.oneofs_by_name['result']
_CHANNELRESPONSE.oneofs_by_name['result'].fields.append(
  _CHANNELRESPONSE.fields_by_name['exception_message'])
_CHANNELRESPONSE.fields_by_name['exception_message'].containing_oneof = _CHANNELRESPONSE.oneofs_by_name['result']
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['MethodCallRequest'] = _METHODCALLREQUEST
DESCRIPTOR.message_types_by_name['Argument'] = _ARGUMENT
DESCRIPTOR.message_types_by_name['Value'] = _VALUE
DESCRIPTOR.message_types_by_name['ImportRequest'] = _IMPORTREQUEST
DESCRIPTOR.message_types_by_name['ConstructorRequest'] = _CONSTRUCTORREQUEST
DESCRIPTOR.message_types_by_name['ChannelResponse'] = _CHANNELRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'exchange_pb2'
  # @@protoc_insertion_point(class_scope:exchange.Request)
  ))
_sym_db.RegisterMessage(Request)

MethodCallRequest = _reflection.GeneratedProtocolMessageType('MethodCallRequest', (_message.Message,), dict(
  DESCRIPTOR = _METHODCALLREQUEST,
  __module__ = 'exchange_pb2'
  # @@protoc_insertion_point(class_scope:exchange.MethodCallRequest)
  ))
_sym_db.RegisterMessage(MethodCallRequest)

Argument = _reflection.GeneratedProtocolMessageType('Argument', (_message.Message,), dict(
  DESCRIPTOR = _ARGUMENT,
  __module__ = 'exchange_pb2'
  # @@protoc_insertion_point(class_scope:exchange.Argument)
  ))
_sym_db.RegisterMessage(Argument)

Value = _reflection.GeneratedProtocolMessageType('Value', (_message.Message,), dict(
  DESCRIPTOR = _VALUE,
  __module__ = 'exchange_pb2'
  # @@protoc_insertion_point(class_scope:exchange.Value)
  ))
_sym_db.RegisterMessage(Value)

ImportRequest = _reflection.GeneratedProtocolMessageType('ImportRequest', (_message.Message,), dict(
  DESCRIPTOR = _IMPORTREQUEST,
  __module__ = 'exchange_pb2'
  # @@protoc_insertion_point(class_scope:exchange.ImportRequest)
  ))
_sym_db.RegisterMessage(ImportRequest)

ConstructorRequest = _reflection.GeneratedProtocolMessageType('ConstructorRequest', (_message.Message,), dict(
  DESCRIPTOR = _CONSTRUCTORREQUEST,
  __module__ = 'exchange_pb2'
  # @@protoc_insertion_point(class_scope:exchange.ConstructorRequest)
  ))
_sym_db.RegisterMessage(ConstructorRequest)

ChannelResponse = _reflection.GeneratedProtocolMessageType('ChannelResponse', (_message.Message,), dict(
  DESCRIPTOR = _CHANNELRESPONSE,
  __module__ = 'exchange_pb2'
  # @@protoc_insertion_point(class_scope:exchange.ChannelResponse)
  ))
_sym_db.RegisterMessage(ChannelResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
